config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  root :to=>"home#index"

  resources :empregados
  resources :empregadors

end

app/models/empregado.rb
class Empregado < ActiveRecord::Base
  belongs_to :empregador
end

app/models/empregador.rb
class Empregador < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  skip_before_action :verify_authenticity_token, if: :json_request?

  protected

  def json_request?
    request.format.json?
  end
end

app/controllers/empregadors_controller.rb
class EmpregadorsController < ApplicationController
  
  before_action :set_empregador, only: [:show, :edit, :update, :destroy]

  # GET /empregadors
  # GET /empregadors.json
  def index
    @empregadors = Empregador.all
  end

  # GET /empregadors/1
  # GET /empregadors/1.json
  def show
  end

  # GET /empregadors/new
  def new
    @empregador = Empregador.new
  end

  # GET /empregadors/1/edit
  def edit
  end

  # POST /empregadors
  # POST /empregadors.json
  def create
    @empregador = Empregador.new(empregador_params)

    respond_to do |format|
      if @empregador.save
        format.html { redirect_to @empregador, notice: 'Empregador was successfully created.' }
        format.json { render :show, status: :created, location: @empregador }
      else
        format.html { render :new }
        format.json { render json: @empregador.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /empregadors/1
  # PATCH/PUT /empregadors/1.json
  def update
    respond_to do |format|
      if @empregador.update(empregador_params)
        format.html { redirect_to @empregador, notice: 'Empregador was successfully updated.' }
        format.json { render :show, status: :ok, location: @empregador }
      else
        format.html { render :edit }
        format.json { render json: @empregador.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /empregadors/1
  # DELETE /empregadors/1.json
  def destroy
    @empregador.destroy
    respond_to do |format|
      format.html { redirect_to empregadors_url, notice: 'Empregador was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_empregador
      @empregador = Empregador.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def empregador_params
      params.require(:empregador).permit(:nome, :endereco, :numero)
    end
end

app/controllers/empregados_controller.rb
class EmpregadosController < ApplicationController
  before_action :set_empregado, only: [:show, :edit, :update, :destroy]

  # GET /empregados
  # GET /empregados.json
  def index
    @empregados = Empregado.all
  end

  # GET /empregados/1
  # GET /empregados/1.json
  def show
  end

  # GET /empregados/new
  def new
    @empregado = Empregado.new
  end

  # GET /empregados/1/edit
  def edit
  end

  # POST /empregados
  # POST /empregados.json
  def create
    @empregado = Empregado.new(empregado_params)

    respond_to do |format|
      if @empregado.save
        format.html { redirect_to @empregado, notice: 'Empregado was successfully created.' }
        format.json { render :show, status: :created, location: @empregado }
      else
        format.html { render :new }
        format.json { render json: @empregado.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /empregados/1
  # PATCH/PUT /empregados/1.json
  def update
    respond_to do |format|
      if @empregado.update(empregado_params)
        format.html { redirect_to @empregado, notice: 'Empregado was successfully updated.' }
        format.json { render :show, status: :ok, location: @empregado }
      else
        format.html { render :edit }
        format.json { render json: @empregado.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /empregados/1
  # DELETE /empregados/1.json
  def destroy
    @empregado.destroy
    respond_to do |format|
      format.html { redirect_to empregados_url, notice: 'Empregado was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_empregado
      @empregado = Empregado.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def empregado_params
      params.require(:empregado).permit(:nome, :endereco, :cidade, :empregador_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/empregadors_helper.rb
module EmpregadorsHelper
end

app/helpers/empregados_helper.rb
module EmpregadosHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/empregadors/_form.html.haml
= simple_form_for(@empregador) do |f|
  = f.error_notification

  .form-inputs
    = f.input :nome
    = f.input :endereco, label: "Endereço"
    = f.input :numero

  .form-actions
    = f.submit "Salvar"

app/views/empregadors/edit.html.haml
%h1 Editing empregador

= render 'form'

= link_to 'Show', @empregador
\|
= link_to 'Back', empregadors_path

app/views/empregadors/index.html.haml
%h1 Listing empregadors

%table
  %thead
    %tr
      %th Nome
      %th Endereco
      %th Numero
      %th
      %th
      %th

  %tbody
    - @empregadors.each do |empregador|
      %tr
        %td= empregador.nome
        %td= empregador.endereco
        %td= empregador.numero
        %td= link_to 'Show', empregador
        %td= link_to 'Edit', edit_empregador_path(empregador)
        %td= link_to 'Excluir', empregador, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Empregador', new_empregador_path

app/views/empregadors/new.html.haml
%h1 New empregador

= render 'form'

= link_to 'Back', empregadors_path

app/views/empregadors/show.html.haml
%p#notice= notice

%p
  %b Nome:
  = @empregador.nome
%p
  %b Endereço:
  = @empregador.endereco
%p
  %b Numero:
  = @empregador.numero

= link_to 'Edit', edit_empregador_path(@empregador)
\|
= link_to 'Back', empregadors_path

app/views/empregados/_form.html.haml
= simple_form_for(@empregado) do |f|
  = f.error_notification

  .form-inputs
    = f.input :nome
    = f.input :endereco, label: "Endereço"
    = f.input :cidade
    = f.association :empregador, label_method: :nome

  .form-actions
    = f.submit "Salvar"

app/views/empregados/edit.html.haml
%h1 Editing empregado

= render 'form'

= link_to 'Show', @empregado
\|
= link_to 'Back', empregados_path

app/views/empregados/index.html.haml
%h1 Listing empregados

%table
  %thead
    %tr
      %th Nome
      %th Endereco
      %th Cidade
      %th Empregador
      %th
      %th
      %th

  %tbody
    - @empregados.each do |empregado|
      %tr
        %td= empregado.nome
        %td= empregado.endereco
        %td= empregado.cidade
        %td= empregado.empregador.nome
        %td= link_to 'Show', empregado
        %td= link_to 'Edit', edit_empregado_path(empregado)
        %td= link_to 'Excluir', empregado, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Empregado', new_empregado_path

app/views/empregados/new.html.haml
%h1 New empregado

= render 'form'

= link_to 'Back', empregados_path

app/views/empregados/show.html.haml
%p#notice= notice

%p
  %b Nome:
  = @empregado.nome
%p
  %b Endereço:
  = @empregado.endereco
%p
  %b Cidade:
  = @empregado.cidade
%p
  %b Empregador:
  = @empregado.empregador.nome

= link_to 'Edit', edit_empregado_path(@empregado)
\|
= link_to 'Back', empregados_path

app/views/home/index.html.haml
%h1 Este é o meu home
adasdas
ads
asd
ad
ad
a
d
ads
a
d
ad
a
d
ad
a


%p Find me in app/views/home/index.html.haml

app/views/layouts/_footer.html.erb
<h3>Footer</h3>

app/views/layouts/_header.html.erb
<h1> Header com heroku e git</h1>
<br>
<ul>
  <li><%= link_to 'Empregador',empregadors_path %></li>
  <li><%= link_to 'Empregados',empregados_path %></li>
</ul>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{ :charset => "utf-8" }

    %meta{:name=>"description", :content=>"Domestica description"}
    %meta{:name=>"keywords", :content=>"Domestica keywords"}
    %meta{:name=>"author", :content=>"Luiz Gustavo"}
    %meta{:property=>"og:type", :content=>"website"}


    %title= content_for?(:title) ? yield(:title) : 'Domestica do Lar'
    %meta{:name => "title", :content => "#{content_for?(:title) ? yield(:title) : 'Domestica do Lar'}"}
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true

    = csrf_meta_tags
  %body
    %header
      = render 'layouts/header'
    %main{:role => "main"}

      = yield
    %footer
      = render 'layouts/footer'